version: "3.9"
services:
  house-be:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    image: house-be
    container_name: house-be
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    ports:
      - 3005:3005
    networks:
    - postgres
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - /data/postgres:/data/postgres
    env_file:
    - docker.env
    networks:
    - postgres
  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "8081:80"
    volumes:
    - /data/pgadmin:/root/.pgadmin
    env_file:
    - docker.env
    networks:
    - postgres
networks:
  postgres:
    driver: bridge